# Generated by Django 3.1.2 on 2020-10-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0004_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='posted',
        ),
    ]
