# Generated by Django 3.1.2 on 2020-10-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0005_auto_20201028_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
